### ISSUE TITLE
Error opening Russian .md and .html files

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#134] opened 2022-03-15 11:58 UTC
## Describe the Problem

Tried to open Russian .html and .md files but got huge error log.

## To Reproduce

1. Download and open attached files
2. See results.

Here is the <details><summary>html log</summary>
<p>
ERROR - bookworm.bookworm.gui.book_viewer - 15/03/2022 15:50:35 - bookworm_threaded_worker_0 (4300):
Unsupported file format
Traceback (most recent call last):
  File "bookworm\reader.py", line 81, in read_document
  File "bookworm\document\formats\html.py", line 262, in read
  File "bookworm\document\formats\html.py", line 129, in read
  File "bookworm\document\formats\html.py", line 265, in parse_html
  File "bookworm\document\formats\html.py", line 184, in parse_to_full_text
  File "lxml\html\__init__.py", line 875, in fromstring
  File "lxml\html\__init__.py", line 761, in document_fromstring
  File "src\lxml\etree.pyx", line 3252, in lxml.etree.fromstring
  File "src\lxml\parser.pxi", line 1907, in lxml.etree._parseMemoryDocument
ValueError: Unicode strings with encoding declaration are not supported. Please use bytes input or XML fragments without declaration.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 102, in resolve_document
  File "bookworm\reader.py", line 90, in read_document
bookworm.reader.ReaderError: Failed to open document</p>
</details>

And here is the <details><summary>.md log</summary>
<p>
ERROR - bookworm.bookworm.gui.book_viewer - 15/03/2022 15:55:40 - MainThread (1888):
Unsupported file format
Traceback (most recent call last):
  File "bookworm\reader.py", line 81, in read_document
  File "bookworm\document\formats\markdown.py", line 34, in read
  File "pathlib.py", line 1267, in read_text
  File "encodings\cp1251.py", line 23, in decode
UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 2110: character maps to <undefined>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 102, in resolve_document
  File "bookworm\reader.py", line 90, in read_document
bookworm.reader.ReaderError: Failed to open document</p>
</details>

@mush42 I want to inform you right away that ordinary text files in Russian open without problems.

(Edit) @mush42 Github does not support uploading .md and .html files, so please rename file1.txt to file1.md and file2.txt to file2.html. There is no other way to attach them here.

[file1.txt](https://github.com/blindpandas/bookworm/files/8253018/file1.txt)
[file2.txt](https://github.com/blindpandas/bookworm/files/8253019/file2.txt)

**Comment by mush42** [comment] 2022-03-15 12:16
Hello @DraganRatkovich 

I couldn't reproduce this in my machine. Please provide the full log.

**Comment by DraganRatkovich** [comment] 2022-03-15 12:24
@mush42 No verbose log to provide, here is the log with debug mode enabled, but no further information is provided here.
[error.commandline.txt](https://github.com/blindpandas/bookworm/files/8253210/error.commandline.txt)

**Comment by mush42** [comment] 2022-03-16 06:19
@DraganRatkovich 
Please check out the latest build from CI. I think it fixes this issue.

**Comment by DraganRatkovich** [comment] 2022-03-16 06:26
@mush42 Nope, still the same issue

**Comment by mush42** [comment] 2022-03-16 16:32
@DraganRatkovich 

Before the latest commit, I faced an issue with the HTML document, and the markdown document was opened successfully.

The latest commit fixed the issue with the HTML document.

I cannot do anything without at least knowing the error, because I could not reproduce this in my local setup.

Please try to provide the logs.

Best
Musharraf

**Comment by mush42** [comment] 2022-03-16 16:33
@DraganRatkovich 
In my local setup, I can now open both files successfully.

**Comment by DraganRatkovich** [comment] 2022-03-16 16:38
@mush42 Could you please give me a local copy of your build without the AppVeyor build because I just want to test it. I can no longer provide a log because there is no additional log to provide.

**Comment by cary-rowen** [comment] 2022-03-19 02:40
Hi @mush42 @DraganRatkovich 
Yes, the latest CI solves the html problem, but not the .md problem. Simplified Chinese .md files are also affected by this, and English .md files are all good.

```
ERROR - bookworm.bookworm.gui.book_viewer - 19/03/2022 10:36:09 - MainThread (12796):
Unsupported file format
Traceback (most recent call last):
  File "bookworm\reader.py", line 81, in read_document
  File "bookworm\document\formats\markdown.py", line 34, in read
  File "pathlib.py", line 1267, in read_text
UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 2566: illegal multibyte sequence

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 102, in resolve_document
  File "bookworm\reader.py", line 90, in read_document
bookworm.reader.ReaderError: Failed to open document
```

**Comment by mush42** [comment] 2022-03-19 10:05
Hello @DraganRatkovich  @cary-rowen 
It seams that this issue is a continuation of the encoding issue in #114 

I pushed a tentative fix. Please check with the problematic files.

Best
Musharraf

**Comment by mush42** [comment] 2022-03-19 10:06
@cary-rowen  I replied to your email four days ago. Hope you received the reply.

**Comment by DraganRatkovich** [comment] 2022-03-19 10:36
Hello @mush42 Thank you, now the files open without problems. @cary-rowen Please let me know if the Chinese file also opens without problems and I will close this issue.

**Comment by cary-rowen** [comment] 2022-03-19 10:52
Hi @mush42 

Oh bad spam filter, I just saw your mail, 
I'll get back to you with an email soon.

Grateful

**Comment by cary-rowen** [comment] 2022-03-19 10:53
Hi @DraganRatkovich 

I confirm that the Simplified Chinese .md file can also be opened smoothly, you can close this issue.

Grateful

**Closed** 2022-03-19 12:40 UTC
