### ISSUE TITLE
Support for plane-text files with content encodings other than Utf-8.

### ISSUE THREAD

**Issue by cary-rowen** [blindpandas/bookworm#114] opened 2022-02-28 00:19 UTC
## Describe the Problem

Unable to open txt document encoded as ANSI

## To Reproduce

1. Download the provided test documentation
2. After unzipping, try to open it in Bookworm
3. You will receive an error message:Could not open file. Either the file  has been damaged during download, or it has been corrupted in some other way.
4. Convert the encoding to UTF-8 using Notepad and the document can be opened

## Expected behavior
Bookworms should be able to open documents encoded in ANSI.

## The File You've Opened
[test.zip](https://github.com/blindpandas/bookworm/files/8149702/test.zip)

## Desktop (please complete the following information):

 - OS:Windows 10 21H2 (x64) build 19044.1526
 - Bookworm version: 2022.1b1 from appveyor.
 - Recent settings you may have changed in Bookworm: None

## Additional context
None

**Comment by cary-rowen** [comment] 2022-02-28 00:20
In addition, the same is true for 2022.1A5

**Comment by DraganRatkovich** [comment] 2022-02-28 06:58
@cary-rowen I've also reproduced this before but didn't pay much attention since all text files were previously encoded in UTF-8, but yes, @mush42 it would be great if you could take a look at this.

**Comment by DraganRatkovich** [comment] 2022-03-06 07:36
@mush42 Here's another issue if you haven't seen it yet. I also reproduced this in a build downloaded from AppVeyor.

**Comment by mush42** [comment] 2022-03-06 08:14
@DraganRatkovich 
I'm working on this.

**Comment by DraganRatkovich** [comment] 2022-03-12 13:29
@mush42 I think df7224b fixes this issue, so you can close this. Also, I can confirm that with the latest build downloaded from AppVeyor, ANSI encoded documents open without issue in both 32 and 64 bit versions of Bookworm.

**Comment by cary-rowen** [comment] 2022-03-12 14:20
Hi @DraganRatkovich 
Did you use the test sample I submitted for testing? I just tested it, and the issue can still be reproduced.
Thanks

**Comment by cary-rowen** [comment] 2022-03-12 14:22
The logs I found are as follows:
```
ERROR - bookworm.bookworm.gui.book_viewer - 12/03/2022 22:21:16 - MainThread (17148):
Unsupported file format
Traceback (most recent call last):
  File "bookworm\reader.py", line 81, in read_document
  File "bookworm\document\formats\plain_text.py", line 35, in read
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb8 in position 60: invalid start byte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\__init__.py", line 102, in resolve_document
  File "bookworm\reader.py", line 90, in read_document
bookworm.reader.ReaderError: Failed to open document
```

**Comment by DraganRatkovich** [comment] 2022-03-12 14:30
Hello @cary-rowen
Oh, sorry, I just downloaded the attached test document and as I see it, this document is not even a text document, because the contents of the documents, when I opened it with Notepad, it looks like the format of the .pdf or .docx file has changed to .txt. When I tried to change the pdf file format to txt, the content looked like your attached document, so make sure it's a real text file, or make sure you can open it with Notepad because Bookworm opens the ANSI document successfully.

**Comment by cary-rowen** [comment] 2022-03-12 14:47
HI @DraganRatkovich 
Yes, I can open it with notepad, this is a novel written in Chinese.
When you download you should get a zip file, you need to unzip it and you should see test.txt.
thanks

**Comment by DraganRatkovich** [comment] 2022-03-12 16:25
@cary-rowen Then it's better to check this issue with @mush42, because I don't have any experience of Chinese and I didn't even know that Chinese document can be encoded in ANSI, my Notepad just showed unknown characters when I opened this document, instead of Chinese characters

**Comment by mush42** [comment] 2022-03-12 17:18
Hello @cary-rowen  @DraganRatkovich 

The file is not encoded in ANSI, but is encoded in a Chinese language specific  encoding; GB2312.

You can confirm this using Notepad++ encoding menu. The checked item in that menu is the encoding of the current file.

In bookworm, even when trying to decode the file using that encoding it fails to decode the content, reporting an encoding error.

Granted, Bookworm needs to better support files with content encodings other than Utf-8.

Best
Musharraf

**Comment by cary-rowen** [comment] 2022-03-12 17:26
Hi @mush42 
Thank you for investigating this, as you said, this is GB-2312, I simply checked the encoding on the status bar of windows notepad, I can see more accurate information in NPP, this is GB-2312.
Thanks

**Comment by DraganRatkovich** [comment] 2022-03-12 17:29
Hi @mush42, Thanks for the info, it's clear now.

**Closed** 2022-03-12 20:56 UTC

**Comment by mush42** [comment] 2022-03-12 21:11
@cary-rowen 

It takes longer than usual to open this file, but this is due to file size, not an encoding issue.

**Comment by cary-rowen** [comment] 2022-03-12 21:27
Hi @mush42 
Thanks for your hard work, I'll test it after the build is complete
cheers

**Comment by mush42** [comment] 2022-03-13 05:46
@cary-rowen does the fix resolve your issue?

**Comment by cary-rowen** [comment] 2022-03-13 05:54
Hi @mush42 
Yes, that fix solved my problem perfectly.
Grateful
