### ISSUE TITLE
Table of contents at the end of the book

### ISSUE THREAD

**Issue by RonnyG2121** [blindpandas/bookworm#251] opened 2024-05-01 14:32 UTC
## Description:

Hello. The problem is the following:

When I open a book, the table of contents is displayed at the end of the book and not at the beginning.

Can I set this to show at the beginning of the book?

It's just uncomfortable to have to lower or select the index and have the content of the book on top.

It will be nice if the software has a function to turn this on or off at will.

thank you so much

**Comment by DraganRatkovich** [comment] 2024-05-09 11:11
Hello,

@RonnyG2121 Could you please provide a sample file of the book you are having a problem with? Some book formats, such as .epub and .mobi, allow the user to choose whether the table of contents should be located at the beginning or at the end of the book.

**Comment by pauliyobo** [comment] 2024-09-20 16:06
Hello.
@RonnyG2121 in order to reproduce this issue, would you be able to provide the file you're having trouble with?
Thank you.

**Comment by RonnyG2121** [comment] 2024-09-20 16:52
Hello
This is the book, but This also happens with other books, this is just a sample.

**Comment by pauliyobo** [comment] 2024-09-30 21:38
Hello. Apologies for the delay.
@RonnyG2121 I am unable to understand what is the issue here.
I can view the TOC fine and it is on the top of the book.
Perhaps you're not using the latest builds? There have been some changes on how we handle ordering on epub books, since it was previously unreliable such as what happened on #243 
Let me know.

**Comment by RonnyG2121** [comment] 2024-10-01 06:19
Thanks for confirm

**Comment by pauliyobo** [comment] 2024-10-01 13:24
@RonnyG2121 Do you confirm it works in newer builds?

**Comment by RonnyG2121** [comment] 2024-10-01 15:45
Yes I do

**Comment by pauliyobo** [comment] 2024-10-01 15:47
Going to close this issue then. Thank you.

**Closed by pauliyobo** 2024-10-01 15:47 UTC
Labels: bug, needs-info
