### ISSUE TITLE
release the handle for files after closing bookworm

### ISSUE THREAD

**Issue by woreda** [blindpandas/bookworm#106] opened 2022-02-24 07:45 UTC
## Describe the Problem

after closing the bookworm software I cannot delete/move files that I have opened with bookworm. the only way I could delete/move files is by killing bookworm process with windows task manager or by signing out and signing back in.

## To Reproduce
1. open any supported file by bookworm.
2. close bookworm.
3. try to delete or move the file you opned earlier.

## Expected behavior

the file should be deleted or moved.

## The File You've Opened
all bookworm supported file formats are afected by this behavior.

## Desktop (please complete the following information):

Microsoft WindowsVersion 21H2 (OS Build 19044.1526) 64 bit
BookwormVersion: 2022.1a5

**Comment by mush42** [comment] 2022-02-25 21:36
Hello @woreda 

I couldn't reproduce this issue in my local setup. I was able to rename an epub document, even while the document is opened in Bookworm. And I was able to rename a PDF document immediately after closing Bookworm.

Please specify exactly what format the document was in.

We have different ways of loading documents into Bookworm. The majority of Documents are loaded entirely into memory first, and then loaded into Bookworm. In fact, the only document format that needs an open file handle during reading is PDF.

Best
Musharraf

**Comment by mush42** [comment] 2022-02-25 21:38
@woreda 
Also, it would be useful if you tell us about the kind of operations you performed during your reading session (e.g. searching, bookmarking, adding to bookshelf..etc.)

Best
Musharraf

**Comment by woreda** [comment] 2022-02-26 10:25
@mush42 
I am very sorry, for my hasty generalization.
I rechecked and can delete or move epub files. but, the problem persists with pdf files as you mentioned earlier.
I was doing OCR on the pdf files before I attempted the delete or move operation.
thank you for your follow up.

**Closed** 2022-02-27 14:48 UTC
