### ISSUE TITLE
PDF has headings in browser, but not in Bookworm

### ISSUE THREAD

**Issue by zersiax** [blindpandas/bookworm#73] opened 2021-07-09 18:27 UTC
## Describe the Problem

I have a PDF here that shows headings in Microsoft Edge when opened. However, in Bookworm, the headings are absent. There is also no Table of Contents, and hitting ctrl+u gives me an empty textbox to fill in a URL rather than it prepopulating with the current URL.

## To Reproduce

Tricky to do, this PDF is a proprietary PDF that I can't easily share. If there's info I can provide on the document some other way I'd be happy to do that.

## Expected behavior

I expected the document to have headings like it does in MS Edge.
## The File You've Opened
PDF
## Desktop (please complete the following information):

 - OS: Windows 11 preview
 - Bookworm version [e.g. 0.4.0b1]

**Comment by mush42** [comment] 2021-07-15 14:08
Unfortunately, support for extracting semantic information from PDFs is not implemented yet.

Regards,

**Comment by mush42** [comment] 2021-12-21 22:56
Duplicate of #28

**Closed by mush42** 2021-12-21 22:56 UTC
