### ISSUE TITLE
Faital error in BookWorm

### ISSUE THREAD

**Issue by RemusLupin96** [blindpandas/bookworm#164] opened 2022-06-18 13:38 UTC
Hello dear developers of Bookworm. Hope you are doing well.
I'm opening this issue regardings of a critical bug for me, which I recently got in BookWorm. It happened just some days ago.
When i want to open the pdf file with Bookworm from a folder in which there's this file, i get following:
The file name, — by User - Bookworm. Press (Ctrl + O) to open a document  edit  read only  multi line  blank.
after 1 or 2 seconds, the dialogue pops up:
Failed to start Bookworm  dialog  A fatal error has occured. Please check the log for more details.
The log has been written to the file:
C:\Users\username\bookworm.errors.log. OK Button.
About which PDF file, it does not matter, any pdf file which i want to open, i get same error.
I successfully found the error logs, honestly i can't understand anything, for that i'll attatch the logs fil.
When i was opening pdf from directly BookWorm, it was opening after some seconds. Yeah, i admit, it was very laggy, and also couldn't go to any page which i wanted with ctrl g, was unable to search,  bookmark, couldn't do any shortcuts, it almost looked like that the document was not opened but opened still.
Also, I've tried uninstalling it, deleted multiple times, with settings and all from appdata, registry, folders, etc. But, didn't worked. I've got latest Appveiour version installed.
Thank you in advance for your help,.
@mush42  @.
@pauliyobo 
@cary-rowen 
@MichelSuch 
Below of this comment will be two files, one a pdf file, and second errors log.
[3_-_the_titan_s_curse.pdf](https://github.com/blindpandas/bookworm/files/8933620/3_-_the_titan_s_curse.pdf)
[bookworm.errors.log](https://github.com/blindpandas/bookworm/files/8933622/bookworm.errors.log)

**Comment by RemusLupin96** [comment] 2022-06-18 13:45
Aa, i forgot to mension, that i'm using windows11 currently. Though before the issue, i was using windows11 too, but no errors at that times.

**Comment by mush42** [comment] 2022-06-18 17:27
Hello @RemusLupin96 

I'm not sure why your version of Bookworm is running the shell disintegration function upon startup. Please tell us exactly what you're trying to do.

The shell disintegration function should only run in the following two cases:
1. When installing or uninstalling the program
2. When the user removes file association from within the program's settings

Anyhow, your problem has been fixed in the code. Although the fixed bug has little to do with failing to start Bookworm.

In the meantime, you can resolve your issue temporarily by using the portable version.

Best
Musharraf

**Comment by RemusLupin96** [comment] 2022-06-18 17:45
@mush42 
Thanks for your quick answer.
Most unfortunately, i have same issue with portable version, i can not normally read the file, shortcuts does not work, and generally it's laggy.
well, what i'm trying to do, is to just open a book, pdf format to be exact, what's happening after that you already know from the log.
i might have forgot to say, that i'm using bookworm version 2022.1b1-x64.

**Comment by mush42** [comment] 2022-06-18 22:05
@RemusLupin96 

I think the error related to reading documents is different from the error reported in the provided log.

Please send the actual log, which can be found in the Appdata\Roaming\Bookworm\logs directory.

**Comment by RemusLupin96** [comment] 2022-06-19 07:23
@mush42,
You are right, if i was getting folowing error which i sent above, now i'm getting different, after downloaded latest version from appveyor, i'll attatch the log to the comment.
[error.log](https://github.com/blindpandas/bookworm/files/8934911/error.log)

**Comment by DraganRatkovich** [comment] 2022-06-19 07:40
Hi
@mush42 I think it has something to do with #165 There are many lines about AccessibleOutput in the attached log.

**Comment by mush42** [comment] 2022-06-19 10:12
@RemusLupin96 

Please remove the folder named "3.9" which you can find under the following folder:
C:\Users\user name\AppData\Local\Temp\gen_py

This should fix the problem

Duplicate of #165

**Closed** 2022-06-19 10:12 UTC
Labels: bug, help wanted

**Comment by RemusLupin96** [comment] 2022-06-19 12:04
@mush42 
I sincerely thank you for your help!
As you said, deleting of the folowing folder successfully solved the problem.
I again sincerely  thank you. Wish you all the best.
