### ISSUE TITLE
Bookworm showing number instead of correct heading level formatting in epub files

### ISSUE THREAD

**Issue by DraganRatkovich** [blindpandas/bookworm#151] opened 2022-04-24 15:02 UTC
I know again that the title of the question is a little tricky when it gets read, but I'll try to explain the specific problem in as much detail as possible.

## Describe the Problem

When opening an epub file that contains heading level 1 formatting to list book chapters, Bookworm, sometimes, only shows numbers instead of heading formatting.
To be more precise, in the places, where the screen reader should say "Heading level 1" and the text of the chapter, it only says 1.
This problem occurs periodically and after a while, it resolves itself again. Sometimes, the documents that I opened and were properly formatted and also displayed without errors in Bookworm, after a while, these documents also did not display the heading formatting correctly and only displayed the number instead of the heading formatting.
During a bug where Bookworm only shows a number instead of the correct formatting, the H also doesn't move to the correct heading and there is no heading in the document, but the table of contents shows the chapters without problems and when you click any of the chapters, the Bookworm jumps to the right chapter, but again, there is no heading formatting, and only the number 1 is displayed.
This issue only occurs with epub files, a Word document, that is also formatted with a heading level 1  displays without problems.

## To Reproduce
Actually, not sure because this problem only occurs intermittently, but just open the epub file and see the result. There is nothing special to say, because, perhaps, the problem does not even arise for someone.

## Expected behavior
Bookworm should display heading formatting without errors in epub files, just like in Word documents.

## Desktop (please complete the following information):
* OS: Windows 10;
* Bookworm version: latest, downloaded from AppVeyor;
* Settings changed: none

## Additional context

@mush42 I know you don't have much time these days, but please, consider tackling this issue when you have free time.

**Comment by DraganRatkovich** [comment] 2022-04-25 09:15
@mush42 Interestingly, the following log errors were found in debug mode

<details><summary>error.commandline log</summary>
<p> ERROR - bookworm.bookworm.bootstrap - 25/04/2022 13:11:18 - MainThread (3296):
Invalid or unknown document uri: nul
Traceback (most recent call last):
  File "bookworm\bootstrap.py", line 72, in _open_arg_file
  File "bookworm\document\uri.py", line 117, in from_base64_encoded_string
  File "base64.py", line 133, in urlsafe_b64decode
  File "base64.py", line 87, in b64decode
binascii.Error: Incorrect padding </p></details>
<details><summary>WX log</summary>
<p> babel\dates.py:161: PytzUsageWarning: The normalize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html

Traceback (most recent call last):
  File "win32com\client\gencache.py", line 236, in GetModuleForCLSID
ModuleNotFoundError: No module named 'win32com.gen_py.C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4.ISpeechObjectToken'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bookworm\gui\book_viewer\navigation.py", line 148, in onStructuredNavigation
  File "bookworm\gui\book_viewer\__init__.py", line 637, in navigate_to_structural_element
  File "bookworm\speech.py", line 24, in announce
  File "accessible_output2\outputs\auto.py", line 12, in __init__
  File "accessible_output2\outputs\sapi5.py", line 36, in __init__
  File "accessible_output2\outputs\sapi5.py", line 43, in _available_voices
  File "win32com\client\util.py", line 84, in __next__
  File "win32com\client\__init__.py", line 502, in _get_good_object_
  File "win32com\client\__init__.py", line 491, in _get_good_single_object_
  File "win32com\client\__init__.py", line 96, in Dispatch
  File "win32com\client\__init__.py", line 37, in __WrapDispatch
  File "win32com\client\gencache.py", line 183, in GetClassForCLSID
  File "win32com\client\gencache.py", line 244, in GetModuleForCLSID
  File "win32com\client\makepy.py", line 320, in GenerateChildFromTypeLibSpec
ModuleNotFoundError: No module named 'win32com.gen_py.C866CA3A-32F7-11D2-9602-00C04F8EE628x0x5x4.ISpeechObjectToken' </p></details>

**Comment by pauliyobo** [comment] 2023-08-13 13:01
@DraganRatkovich  are you still encountering this problem?

**Comment by DraganRatkovich** [comment] 2023-08-13 13:04
> @DraganRatkovich  are you still encountering this problem?

Hi,

@pauliyobo Yes, sometimes.

**Comment by pauliyobo** [comment] 2024-09-20 16:25
Hello
@DraganRatkovich to this day, I'm still unable to reproduce this issue. Would you be able to provide an example file with which you are encountering the problem?
Thank you.

**Comment by pauliyobo** [comment] 2024-12-28 22:38
Hello.
Hello. I believe I'll be closing this issue for the moment.
The reproduction steps are somewhat unclear, which is probably fine given that when the issue was raised the behaviour was intermittent.
If anyone is still able to reproduce this issue, open a new one providing as well the file that causes this behaviour.
Thanks.

**Comment by DraganRatkovich** [comment] 2024-12-30 07:05
@pauliyobo Don't close an issue that isn't fixed, at least no one has tried to fix it due to the difficulty of reproduction, but that doesn't mean the issue is fixed. As for the files, I will upload them later these days.

**Comment by pauliyobo** [comment] 2024-12-30 07:12
@DraganRatkovich The issue was stale, with no reproduction information. Keeping it open would just cause confusion with no information on how to identify the problem.
If you have reproduction information, I'd encourage  you to open a new issue with more updated context.
The issue, and any issues closed this way haven't been closed lightly.
Thanks.

**Closed by pauliyobo** 2024-12-30 07:12 UTC
Labels: bug, needs-info
